---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker

env:
  global:
    - secure: "Xxg46jL2dao8FYWIrBUNs/J2vF6+PyDDsuF9Vys1f0TD2vVTH1xovBg\
      IXVoiBSph0gxJpaWkDS4Sdhs8lQA5lHUvCptEH368VMa/EyRy1pPr8bdferaJKMX\
      8CBGQZurE/5P6nbNRJxYzfQNgZO3Qpoj8ev0w7HxU1ft0ptRhsDCssqd5aoo0JrT\
      fYhOrfsrXDsXOeGnrKOTAQWxcgQNV4dnEArkwYC69nBVKJy7HUdfEHzbR7dBAeQs\
      w6H0LsscDlNb+EYWTFuCJgyLTkrWSicb6dEin0rN6aBQGCqMKOeiUimf7DB5DMpB\
      mTxeHub/WpyqgTWlUp+JbOFf1qUXm/JpUxPye/aX3yzGYgGJjvJ1wqZRU5YyKoVO\
      m5IVysuqcZ3zJeJCPBsPhi47ULUvEEU2pNSQa2kicn8ApDa0k8BDHuKHNaBHMs+i\
      P57I5dD1FXwigji2dWC48BshKNIzxnF1m4B4dcLYi7NAU1VvbqzzbO06mA002QbE\
      YuM5AxpfBiu12JKLiyEkHRa95hjfKrYwG3mUZTnaVTor+plxF/4/XPxbbnZJc9sT\
      PuJMqHPRxRctBFv9E2mTfNTuJxHdw49FwXbCFHr9hn7Vt5FC3xVrRTMWI0ZCkQAo\
      cfJQYCdcdLx6s74N2MC/jru8sMLKVLaXHlHajGRR9W60eekI1udA="
    - secure: "HP9NNZEAPG56k4jMyBfKOyfqNXYn+U73Juogd4Hq0ILcpyBexOaioFu\
      fFDZMo2j2tkuOnPopFUSsBVePnEvc3WZgucP2K5/ieje+2q7AUtuzPQ0cxsJyMpb\
      ySHaBEZWMyIVxTVVLcLRniVY/lXzCiD22UowqyYxq7tktZCbTyp1GKmQSzP0Zf7h\
      2+DeUCeuRgC3zB9h2fTzi+StFbR6rxwUZMy8vNsG7y1eMc7R1EsC7EdmoTU2C2DU\
      K0Fl6oTcKnvQ+1JUVTwh/xFBdAACDOq+4WGY5DcHBuU59ZVnmJeu3W6lPG1Ahs7h\
      JJI/p0gZ1nU2AC46UKcMh9NOjLuFrbv9in0bzW15gnPb6iJs3iZd1EbWnjiyrOMu\
      XKF6MgPePk+ac4tN0tiRNAinsx1h2rWlBpiZurrT+wu8QCIHMkXp9g8MoTvFZhsY\
      5yUt4MCn7cv4Us1RFBq14KxvyX66ysp/QLJSyFShEAxnv0hf0l2Q7GLqWtmLk4Uz\
      skEWQx83LFArQYAWqBkQMsY7pDJbPMJCB5qITNMYz3kVBFjFckuGQyNRxiI7PIuX\
      OgL2qXBgKkZRLwT6JryeXp1nEj09W8tTId67nNEpybXJ8YBBkoOmhUmjQETZLVKv\
      1ar1KKapxX57gDPOC5Xe521dhWOjyEkWAaHW4x0QrsAilwOwsC8A="
    - secure: "RsAi/S2ImNMb9k6PQuQhyard09R7FoNNP9MULq+y6jAJAELG/deo9XH\
      00Z6ReVs7fVOifv0u0+Wb4DKJgDNEfVAFfLGKwJa2cLH+62qQ5AvSF1cnwIiw/hp\
      whWEtPJ6ke5wUeqCA3IEBSNrHR67IB7JCTVhUnuGtT4g/KlAmtOh9pWlmYOyOLa3\
      EQTM/WywogxqNwIjv6/ND5/com22csys/K2Fs0ogMh+OPkV4mEy74sTu0rvuCzaq\
      ZNBfwMpjad+XvBuYZWxgerNOxqxpWhhlSfrIXKC9myVuuXF4sti6/kZWRcVVijFi\
      lOAvuAX6HRKo66JUE2M6iru+064TH4RM6q45qxpujNn4ByepSUxz77EtnEYN6P/e\
      zsFEIGkweVtXnmHO/12xkHgDOS7nRdqrfNyYVbKnZm19QGQR/xnuDHjc/+oK+hPV\
      4KqjE/jD2USXjYYhe6UERwO1LDnNkEN3fmHA6UfK/nEj9tVfPQMmK9naZLIEKN+K\
      N9pNd71AIFDQ9fU5ugvIkfXFYYDAANzM3GyArErlO4xbYUgG4lfHc9gBRB7uGycF\
      H4P+Ng5CfKdzh9rLoKWozWrp9pPGBUOM22QcZPQEDNFVG9eRtca7g/I6llth3qhY\
      7JxigKBDNULeRHrg4RyMJ88zbhowaNSWjMSKRHuc9OAdgeD9zWA4="

# Install terraform and terraform-doc
before_install:
  - >
    wget
    https://releases.hashicorp.com/terraform/0.12.1/terraform_0.12.1_linux_amd64.zip
    -O terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - go get github.com/segmentio/terraform-docs

# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

install:
  - pip install --upgrade -r requirements-test.txt

script:
  - pre-commit run --all-files
  - molecule test
