---
# tasks file for nessus

- name: Check if Nessus is installed
  command: "dpkg-query --show --showformat='${db:Status-Status}|${Version}\n' \
  nessus"
  register: dpkg_query_result
  ignore_errors: yes
  changed_when: false

- name: Set fact for "has latest Nessus installed"
  set_fact:
    has_latest: "{{ dpkg_query_result.stdout is \
    search('installed|{{ version }}') }}"

- name: Fetch specified Nessus package from S3
  aws_s3:
    bucket: "{{ package_bucket }}"
    object: "{{ package_file }}"
    dest: "/tmp/{{ package_file }}"
    mode: get
  become: no
  delegate_to: localhost
  when: not has_latest

- name: Copy local Nessus package (.deb) to remote side
  copy:
    src: "/tmp/{{ package_file }}"
    dest: "/tmp/{{ package_file }}"
    mode: 0644
  when: not has_latest

- name: Install specified Nessus version
  apt:
    deb: "/tmp/{{ package_file }}"
    state: present
  when: not has_latest

- name: Delete Nessus package (.deb) on remote side
  file:
    path: "/tmp/{{ package_file }}"
    state: absent
  when: not has_latest

- name: Delete local copy of Nessus package
  file:
    path: "/tmp/{{ package_file }}"
    state: absent
  become: no
  delegate_to: localhost
  when: not has_latest
