---
- name: Load var file based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

# python3-rpm is not always pre-installed on RedHat platforms that use
# the dnf5 package manager, but it is a prerequisite for the
# ansible.builtin.package_facts module.
- name: Install prerequisites for ansible.builtin.package_facts (RedHat)
  ansible.builtin.package:
    name:
      - python3-rpm
  when:
    - ansible_os_family == "RedHat"

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Install Nessus
  # Only run this block if Nessus is not installed or is not the
  # correct version.  Note that the Nessus package name can be
  # capitalized or not capitalized.
  when: |
    (ansible_facts.packages.nessus is not defined
     or ansible_facts.packages.nessus[0].version is not defined
     or not ansible_facts.packages.nessus[0].version is search(nessus_version) | bool)
     and (ansible_facts.packages.Nessus is not defined
     or ansible_facts.packages.Nessus[0].version is not defined
     or not ansible_facts.packages.Nessus[0].version is search(nessus_version) | bool)
  block:
    - name: Fetch list of keys in bucket
      amazon.aws.s3_object:
        bucket: "{{ nessus_package_bucket }}"
        mode: list
      become: false
      delegate_to: localhost
      register: keys

    - name: Install Nessus package file
      vars:
        package_file: >-
          {{ keys.s3_keys | select('search', package_file_regex) | first }}
      block:
        - name: Fetch specified Nessus package from S3
          amazon.aws.s3_object:
            bucket: "{{ nessus_package_bucket }}"
            dest: /tmp/{{ package_file }}
            mode: get
            object: "{{ package_file }}"
          become: false
          delegate_to: localhost

        - name: Copy local Nessus package to remote side
          ansible.builtin.copy:
            dest: /tmp/{{ package_file }}
            mode: u=rw,g=r,o=r
            src: /tmp/{{ package_file }}

        - name: Install specified Nessus version
          block:
            - name: Install apt package
              ansible.builtin.apt:
                deb: /tmp/{{ package_file }}
                state: present
              when: ansible_pkg_mgr == "apt"

            - name: Install dnf package
              ansible.builtin.dnf:
                # If we downloaded the RPM signing key from Tenable
                # then we'd be downloading it from the same website as
                # the package anyway.
                disable_gpg_check: true
                name: /tmp/{{ package_file }}
                state: present
              when: ansible_pkg_mgr in ["dnf", "yum"]

            - name: Install dnf5 package
              ansible.builtin.dnf5:
                # If we downloaded the RPM signing key from Tenable
                # then we'd be downloading it from the same website as
                # the package anyway.
                disable_gpg_check: true
                name: /tmp/{{ package_file }}
                state: present
              when: ansible_pkg_mgr in ["dnf5"]

        - name: Delete Nessus package on remote side
          ansible.builtin.file:
            path: /tmp/{{ package_file }}
            state: absent

        - name: Delete local copy of Nessus package
          ansible.builtin.file:
            path: /tmp/{{ package_file }}
            state: absent
          become: false
          delegate_to: localhost

# "expect" and "jq" are used downstream to automate creation of Nessus
# users
- name: Install expect and jq packages
  ansible.builtin.package:
    name: "{{ package_names }}"
    state: present
