---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-nessus
      # We do prepend the name of the role to the role variables, but
      # Molecule does its own role discovery with inconsistent naming.
      # This is the reason for the noqa below.
      ansible.builtin.include_role: # noqa var-naming[no-role-prefix]
        name: ansible-role-nessus
      vars:
        nessus_package_bucket: >-
          {{ lookup('amazon.aws.ssm_parameter', '/third_party_bucket_name') }}
        nessus_version: 10.9.4
