---
- name: Import upgrade playbook
  ansible.builtin.import_playbook: upgrade.yml

- name: Import python playbook
  ansible.builtin.import_playbook: python.yml

# boto3 is installed anywhere we would be applying this Ansible role
- name: Install boto3 and pip
  hosts: all
  roles:
    - pip
  tasks:
    - name: Install boto3
      ansible.builtin.pip:
        name: boto3
