---
- hosts: all
  name: Install pip3/python3
  become: yes
  become_method: sudo
  roles:
    - name: pip
      vars:
        install_python2: true
    - name: python
      vars:
        install_pip2: true
